//! JSON-RPC 2.0 wire types and helpers.
//!
//! Hand-rolled to keep the dependency footprint small and to preserve the
//! same "return `Result`, never `panic!`" policy used elsewhere in the
//! codebase (see `CLAUDE.md` on provider adapters).

use serde::{Deserialize, Serialize};
use serde_json::Value;

use super::errors::ProtocolParseError;

/// The JSON-RPC version the MCP spec pins.
pub const JSONRPC_VERSION: &str = "2.0";

/// Identifies one in-flight JSON-RPC request.
///
/// The spec permits either a string or a numeric id. Notifications have no id.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RequestId {
    /// A numeric id generated by the client.
    Number(u64),
    /// A string id generated by the client.
    String(String),
}

impl RequestId {
    /// Builds a numeric id.
    pub fn from_u64(value: u64) -> Self {
        Self::Number(value)
    }
}

impl std::fmt::Display for RequestId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Number(n) => write!(f, "{n}"),
            Self::String(s) => write!(f, "{s}"),
        }
    }
}

/// A JSON-RPC 2.0 client → server request frame.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct JsonRpcRequest {
    /// Must be `"2.0"`.
    pub jsonrpc: String,
    /// The correlation id.
    pub id: RequestId,
    /// The RPC method name.
    pub method: String,
    /// The method-specific parameters.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub params: Option<Value>,
}

/// A JSON-RPC 2.0 server → client response frame.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct JsonRpcResponse {
    /// Must be `"2.0"`.
    pub jsonrpc: String,
    /// The correlation id from the originating request.
    pub id: RequestId,
    /// The successful result payload, if any.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub result: Option<Value>,
    /// The error payload, if any.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub error: Option<JsonRpcError>,
}

/// A JSON-RPC 2.0 notification frame (no id, no response expected).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct JsonRpcNotification {
    /// Must be `"2.0"`.
    pub jsonrpc: String,
    /// The notification method name.
    pub method: String,
    /// The method-specific parameters.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub params: Option<Value>,
}

/// A JSON-RPC 2.0 error object carried inside a response.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct JsonRpcError {
    /// The numeric error code defined by the JSON-RPC spec or the MCP server.
    pub code: i64,
    /// The human-readable error message.
    pub message: String,
    /// Optional structured error data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub data: Option<Value>,
}

/// Every possible inbound frame from a peer.
#[derive(Debug, Clone)]
pub enum IncomingMessage {
    /// A response to a prior request we issued.
    Response(JsonRpcResponse),
    /// A notification from the peer (no reply expected).
    Notification(JsonRpcNotification),
    /// A server-initiated request. v1 stubs these by ignoring them.
    Request(JsonRpcRequest),
}

/// Parses one raw JSON object into an `IncomingMessage`.
///
/// Returns `ProtocolParseError::InvalidJson` if the bytes are not valid JSON,
/// `UnsupportedVersion` if the frame advertises a `jsonrpc` other than `"2.0"`,
/// and `MissingField` when neither `method` nor a response-shape
/// (`result`/`error` + `id`) can be identified.
pub fn parse_message(bytes: &[u8]) -> Result<IncomingMessage, ProtocolParseError> {
    let value: Value = serde_json::from_slice(bytes)?;
    let object = value
        .as_object()
        .ok_or(ProtocolParseError::MissingField { name: "jsonrpc" })?;

    match object.get("jsonrpc").and_then(Value::as_str) {
        Some(JSONRPC_VERSION) => {}
        Some(other) => {
            return Err(ProtocolParseError::UnsupportedVersion {
                got: other.to_owned(),
            });
        }
        None => return Err(ProtocolParseError::MissingField { name: "jsonrpc" }),
    }

    let has_method = object.contains_key("method");
    let has_id = object.contains_key("id");

    if has_method && has_id {
        let req: JsonRpcRequest = serde_json::from_value(value)?;
        Ok(IncomingMessage::Request(req))
    } else if has_method {
        let notif: JsonRpcNotification = serde_json::from_value(value)?;
        Ok(IncomingMessage::Notification(notif))
    } else if has_id {
        let resp: JsonRpcResponse = serde_json::from_value(value)?;
        Ok(IncomingMessage::Response(resp))
    } else {
        Err(ProtocolParseError::MissingField { name: "method" })
    }
}

/// Serializes a request frame into bytes suitable for NDJSON transport.
pub fn encode_request<P: Serialize>(
    id: &RequestId,
    method: &str,
    params: Option<&P>,
) -> Result<Vec<u8>, serde_json::Error> {
    let params_value = match params {
        Some(p) => Some(serde_json::to_value(p)?),
        None => None,
    };
    let frame = JsonRpcRequest {
        jsonrpc: JSONRPC_VERSION.to_owned(),
        id: id.clone(),
        method: method.to_owned(),
        params: params_value,
    };
    serde_json::to_vec(&frame)
}

/// Serializes a notification frame into bytes suitable for NDJSON transport.
pub fn encode_notification<P: Serialize>(
    method: &str,
    params: Option<&P>,
) -> Result<Vec<u8>, serde_json::Error> {
    let params_value = match params {
        Some(p) => Some(serde_json::to_value(p)?),
        None => None,
    };
    let frame = JsonRpcNotification {
        jsonrpc: JSONRPC_VERSION.to_owned(),
        method: method.to_owned(),
        params: params_value,
    };
    serde_json::to_vec(&frame)
}

/// Serializes a successful response frame.
pub fn encode_response_success(id: &RequestId, result: Value) -> Result<Vec<u8>, serde_json::Error> {
    let frame = JsonRpcResponse {
        jsonrpc: JSONRPC_VERSION.to_owned(),
        id: id.clone(),
        result: Some(result),
        error: None,
    };
    serde_json::to_vec(&frame)
}
